name: Fetch Poem from Dify & Save to Notion

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12 PM UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  run-dify-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Call Dify Workflow
        id: get_poem
        run: |
          # Call the Dify workflow API
          RESPONSE=$(curl -s -X POST 'https://dify.kn.ly/v1/workflows/run' \
            --header "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data-raw '{
                "inputs": {},
                "response_mode": "blocking",
                "user": "automation_script"
              }')
          
          echo "Raw API Response: $RESPONSE"
          
          # Extract the poem text from the output with key "1"
          POEM=$(echo "$RESPONSE" | jq -r '.data.outputs["1"]')
          
          if [[ -z "$POEM" ]]; then
              echo "Error: No valid poem output"
              exit 1
          fi
          
          # Safely export the multiline poem to the GitHub Actions environment
          echo "poem<<EOF" >> $GITHUB_ENV
          echo "$POEM" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Save Poem to Notion
        run: |
          # Build the JSON payload safely using jq
          PAYLOAD=$(jq -n \
            --arg dbid "${{ secrets.NOTION_DATABASE_ID }}" \
            --arg date "$(date -u +%Y-%m-%d)" \
            --arg poem "$poem" \
            '{
              parent: { database_id: $dbid },
              properties: {
                Title: { title: [{ text: { content: "Statement" } }] },
                Date: { date: { start: $date } },
                Content: { rich_text: [{ text: { content: $poem } }] }
              }
            }')
          
          echo "Payload: $PAYLOAD"
          
          # Post the payload to the Notion API
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d "$PAYLOAD"
