name: Fetch Poem from Dify & Save to Notion

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  run-dify-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Call Dify Workflow
        id: get_poem  # Fixed indentation
        run: |
          RESPONSE=$(curl -s -X POST "https://dify.kn.ly/v1" \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}')
          
          echo "Raw API Response: $RESPONSE"  # Debugging step
          
          POEM=$(echo "$RESPONSE" | jq -r '.output' || echo "Error: No valid output")
          
          echo "poem=$POEM" >> $GITHUB_ENV

      - name: Save Poem to Notion
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          -d '{
            "parent": { "database_id": "'${{ secrets.NOTION_DATABASE_ID }}'" },
            "properties": {
              "Title": { "title": [{ "text": { "content": "Statement" }}] },
              "Date": { "date": { "start": "'$(date -u +%Y-%m-%d)'" }},
              "Content": { "rich_text": [{ "text": { "content": "'"$POEM"'" }}] }
            }
          }'
